name: craft

on:
  push:
    branches: [master]

jobs:
  compiling:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++,clang, VS]
        exclude:
          - os: windows-latest
            compiler: g++
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang
    steps:
      - name: one
        uses: actions/checkout@v3
      - name: two
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y ${{matrix.compiler}} cmake
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/_build -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          cmake --build ${{github.workspace}}/_build
      - name: three
        if: matrix.os == 'windows-latest'
        run: |
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/_build -G "Visual Studio 17 2022" -A x64
          cmake --build ${{github.workspace}}/_build --config=Release
